In [5]:
"""
Remember that in a systems of linear equations: Ax = b

_where A is a matrix that contains all the coefficients
_x is a vector that contains all the solutions: x1, x2, x3, ... xn
_b is a vector that contains all the constants

"""

import numpy as np

A = np.array([[2, 7, -1, 3, 1],
              [2, 3, 4, 1, 7],
              [6, 2, -3, 2, -1],
              [2, 1, 2, -1, 2],
              [3, 4, 1, -2, 1]], float)

b = np.array([5, 7, 2, 3, 4], float)
n = len(b)
x = np.zeros(n, float)                     #This vector is initially filled with zeroes
                                          
#Elimination
for k in range(n - 1):
    for i in range(k + 1, n):              #the first row is fixed, hence starting from k + 1
        factor = A[k, k] / A[i, k]         #finding the factor so that the coefficients in the same columns are equal 
        b[i] = b[k] - factor * b[i]        
        for j in range(k, n):
            A[i, j] = A[k, j] - factor * A[i, j]    #elimination

print(A)

x[n - 1] = b[n - 1] / A[n - 1, n - 1]

for i in range(n - 2, -1, -1):             #Iteration starting from 2nd to last element to the first backwards
    terms = 0
    for j in range(i + 1, n):
       terms += A[i, j] * x[j]
    x[i] = (b[i] - terms) / A[i, i]
    
print(x)


[[ 2.          7.         -1.          3.          1.        ]
 [ 0.          4.         -5.          2.         -6.        ]
 [ 0.          0.         -5.          0.52631579 -6.84210526]
 [ 0.          0.          0.          1.6374269   2.04678363]
 [ 0.          0.          0.          0.          0.95890411]]
[0.44444444 0.55555556 0.66666667 0.22222222 0.22222222]


In [14]:
import numpy as np

"""
A = np.array([[2, 7, -1, 3, 1],
              [2, 3, 4, 1, 7],
              [6, 2, -3, 2, -1],
              [2, 1, 2, -1, 2],
              [3, 4, 1, -2, 1]], float)

b = np.array([5, 7, 2, 3, 4], float)
"""
A = np.array([[0, 7, -1, 3, 1],
              [2, 3, 4, 1, 7],
              [6, 2, 0, 2, -1],
              [2, 1, 2, 0, 2],
              [3, 4, 1, -2, 1]], float)

b = np.array([5, 7, 2, 3, 4], float)

def elimination(A, b):
    n = len(b)
    x = np.zeros(n, float)                     #This vector is initially filled with zeroes
                                          
    #Elimination
    for k in range(n - 1):
        for i in range(k + 1, n):
            factor = A[k, k] / A[i, k]
            #b[i] = b[k] - factor * b[i]        
            for j in range(k, n):
                A[i, j] = A[k, j] - factor * A[i, j]
    return A

print(elimination(A, b))

"""
Please note that this elimination method doesn't work if the diagonals contains 0. So please only refer to the 
method below for all test-cases.
"""

[[ 0.  7. -1.  3.  1.]
 [ 0.  7. -1.  3.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. nan nan nan]
 [ 0.  0. nan nan nan]]


/var/folders/0t/37zzt2wj3ygb5dmbchvqxtdc0000gn/T/ipykernel_1297/261290990.py:27: RuntimeWarning: invalid value encountered in double_scalars
  factor = A[k, k] / A[i, k]


In [16]:
import numpy as np


A = np.array([[4, 3, 2, 1],
              [1, 2, 2, 2],
              [1, 1, 3, 0],
              [2, 1, 2, 3]], float)

b = np.array([10, 7, 5, 8], float)

# A = np.array([[0, 7, -1, 3, 1],
#               [2, 3, 4, 1, 7],
#               [6, 2, 0, 2, -1],
#               [2, 1, 2, 0, 2],
#               [3, 4, 1, -2, 1]], float)

# b = np.array([5, 7, 2, 3, 4], float)

def Guassian_Elimination(A, b):
    n = len(b)
    x = np.zeros(n, float)                     #This vector is initially filled with zeroes
                                          
    #Elimination
    for k in range(n - 1):
        if A[k, k] == 0:                       #if diagonals are 0
            for j in range(n):
                A[k , j], A[k + 1, j] = A[k + 1, j], A[k, j]
            b[k], b[k + 1] = b[k + 1], b[k]
                
        for i in range(k + 1, n):              #the first row is fixed, hence starting from k + 1
            if A[i, k] == 0:                   #if a coefficient is zero, skip the lines below within the for-loop
                continue                       #we do not need to eliminate since, it is already 0
            factor = A[k, k] / A[i, k]         #finding the factor so that the coefficients in the same columns are equal 
            b[i] = b[k] - factor * b[i]        
            for j in range(k, n):
                A[i, j] = A[k, j] - factor * A[i, j]    #elimination

    #Backward_Substitution
    x[n - 1] = b[n - 1] / A[n - 1, n - 1]

    for i in range(n - 2, -1, -1):             #Iteration starting from 2nd to last element to the first backwards
        terms = 0
        for j in range(i + 1, n):
           terms += A[i, j] * x[j]
        x[i] = (b[i] - terms) / A[i, i]
    
    print(f"{x}T\n")
    for i in range(n):
        print(f"x{i + 1}: {x[i]}")
    
Guassian_Elimination(A, b)

[1. 1. 1. 1.]T

x1: 1.0
x2: 1.0
x3: 1.0
x4: 1.0
