In [8]:
import numpy as np

def LU_factorization(A):
    n = len(A)
    L = np.eye(n)
    U = A.copy()
    for j in range(n):
        for i in range(j+1, n):
            L[i, j] = U[i, j] / U[j, j]
            for k in range(j, n):
                U[i, k] = U[i, k] - L[i, j] * U[j, k]
    return L, U

A = np.array([[2, 1, 4], [1, 2, 2], [2, 4, 6]])           #don't put float as a parameter for this array
L, U = LU_factorization(A)
print("Upper triangle:\n", L, "\n")
print("Lower triangle:\n", U, "\n")

Upper triangle:
 [[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  3.  1. ]] 

Lower triangle:
 [[2 1 4]
 [0 1 0]
 [0 0 2]] 



In [ ]:
"""
Advantages of LU factorization:

_Direct method: LU factorization is a direct method, which means it will always find the exact solution if 
one exists.

_Computationally efficient: LU factorization is computationally efficient, especially for sparse matrices 
and large systems of equations.

_Good numerical stability: LU factorization is less prone to round-off errors than other direct methods such 
as Gaussian elimination.

_Can be used to solve multiple systems with the same coefficient matrix.

_Can be used to calculate determinant and inverses of matrix.


Disadvantages of LU factorization:

_Does not work for singular matrices: LU factorization cannot be used to solve systems of equations if 
the coefficient matrix A is singular.

_Requires additional memory: LU factorization requires additional memory to store the L and U matrices.

_Numerical instability: LU factorization can be sensitive to perturbations of the matrix A, which can 
lead to numerical instability and large errors in the solution.

_Not always stable for large system of equations with high condition numbers.
"""