In [5]:
import numpy as np

def residual(A, x, b):
    dot_product = b - np.dot(A, x)
    add_squares = 0
    for i in range(len(dot_product)):
        add_squares += dot_product[i] ** 2
    sol = np.sqrt(add_squares)
    return sol

#residual = magnitude(b - Ax)

A = np.array([[2, -1, 0], [-1, 1, 3], [1, 0, 1]], float)
b = np.array([1, 3, 2], float)
x = np.array([0.5, 3.5, 1.5], float)
print(f"Residual: {residual(A, x, b)}")

Residual: 5.70087712549569


In [ ]:
"""
In the Gauss-Seidel and Jacobi iteration method, the residual is the difference between the solution obtained 
at the current iteration and the solution obtained at the previous iteration. It is used as a measure of how 
close the solution is to the true solution of the linear system Ax = b. 

The residual is used as a stopping criterion for the iteration process. The iteration continues until the 
residual falls below a certain tolerance level or the maximum number of iterations is reached. The smaller 
the residual, the closer the solution is to the true solution of the system.

The residual can be calculated using the following formula:

residual = || b - Ax ||

where A is the matrix, x is the current approximation to the solution, and b is the right-hand side of the equation. The operator || || denotes the Euclidean norm, which is the square root of the sum of the squares of the elements in the vector.

"""

In [18]:
#The product of two matrices, vectors provided that they are multiplicable
import numpy as np

A = np.array([[-1, 0, 1], [1, 1, 1]])
b = np.array([0.5, 1.2, 1.5])

print(np.dot(A, b))


[1.  3.2]


In [19]:
#Finding an inverse of a matrix
import numpy as np

A = np.array([[2, 0], [0, 3]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[0.5        0.        ]
 [0.         0.33333333]]


In [20]:
print(np.dot(A_inv, np.array([1, 3.2])))

[0.5        1.06666667]


In [4]:
import numpy as np

print(np.dot([[2, 1, 0], [-1, 1, 3], [1, 0, 1]], [0.5, 3.5, 1.5]))

[4.5 7.5 2. ]


In [6]:
#Least Square Fitting

import numpy as np

# Define the matrix
A = np.array([[1,-1,1],[1,-0.5,0.25],[1,0,0],[1,0.5,0.25],[1,1,1]])

# Transpose the matrix using the numpy.transpose() function           Ab = x
A_transposed = np.transpose(A)
C = np.dot(A_transposed, A)                         
B = np.array([1,0.5,0,0.5,2])
D = np.dot(A_transposed, B)
print(C)
print(D)
X = np.linalg.solve(C, D)
print(X)

[[5.    0.    2.5  ]
 [0.    2.5   0.   ]
 [2.5   0.    2.125]]
[4.   1.   3.25]
[0.08571429 0.4        1.42857143]


In [11]:
import numpy as np
from scipy.optimize import least_squares

# Define the function to fit
def func(x, a, b,c):
    return a*x*x + b*x + c

# Define the residuals (difference between data and model)
def residuals(p, y, x):
    return y - func(x, *p)

# Initial guess for the parameters
x = np.array([-1, -0.5, 0,0.5,1.0])
y = np.array([1,0.5,0,0.5,2])
p0 = [1, 1, 1]

# Perform the least squares optimization
res = least_squares(residuals, p0, args=(y, x))
res.x = np.around(res.x, decimals=4)

# Print the results
print("Fitted parameters: x1 = {2}, x2 = {1} x3 = {0}".format(res.x[0], res.x[1],res.x[2]))


Fitted parameters: x1 = 0.0857, x2 = 0.4 x3 = 1.4286


In [12]:
import numpy as np
def largest(b,t,l,u):
    y = np.float64(0)
    b = np.float64(b)
    t = int(t)
    l = np.float64(l) 
    u = np.float64(u)
    nos = 1
    for j in range(t):
        if j == 0:
            nos =nos* (b-1)
        else:
            nos = nos*(b)
    nos = nos * 2 *(u+abs(l)+1) + 1
    for i in range(t):
        y = y + b**(-i-1)*(b-1)
    print('Total numbers possible in the system:',nos)
    return b**u*y

print(f"The largest number is {largest(10,3,-3,3)}.")

Total numbers possible in the system: 12601.0
The largest number is 999.0.
