In [10]:
import numpy as np

#Inititializing 1-dimensional numpy arrays

a = np.array([1, 3, 5])
b = np.array([1, 2, 3])

print(f"a = {a}")
print(f"b = {b}")
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"3a + 1= {(3 * a) + 1}")

a = [1 3 5]
b = [1 2 3]
a + b = [2 5 8]
a - b = [0 1 2]
3a + 1= [ 4 10 16]


In [29]:
#Initializing 2-dimensional numpy arrays

c = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
d = np.array([[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])

print(f"c = {c} \n")
print(f"2c = {2 * c} \n")
print(f"c + d = {c + d} \n")

c = [[9. 8. 7.]
 [6. 5. 4.]] 

2c = [[18. 16. 14.]
 [12. 10.  8.]] 

c + d = [[10.  9.  8.]
 [ 7.  6.  5.]] 



In [30]:
#returns the dimension of a numpy-array

print(f"dimension of a: {a.ndim}")
print(f"dimension of b: {b.ndim}")
print(f"dimension of c: {c.ndim}")
print(f"dimension of d: {d.ndim}")

dimension of a: 1
dimension of b: 1
dimension of c: 2
dimension of d: 2


In [32]:
#returns the shape of a numpy-array

print(f"shape of a: {a.shape}")   #3-rows  
print(f"shape of b: {b.shape}")   #3-rows
print(f"shape of c: {c.shape}")   #2-rows, 3-columns
print(f"shape of d: {d.shape}")   #2-rows, 3-columns

shape of a: (3,)
shape of b: (3,)
shape of c: (2, 3)
shape of d: (2, 3)


In [33]:
#return the data-type of a numpy-array

print(f"data-type of a: {a.dtype}")
print(f"data-type of b: {b.dtype}")
print(f"data-type of c: {c.dtype}")
print(f"data-type of d: {d.dtype}")

data-type of a: int64
data-type of b: int64
data-type of c: float64
data-type of d: float64


In [35]:
#Specify the data-type of a numpy-array

e = np.array([1, 3, 5], dtype = "int16")
f = np.array([1, 2, 3], dtype = "int16")

print(f"data-type of e: {e.dtype}")
print(f"data-type of f: {f.dtype}")

data-type of e: int16
data-type of f: int16


In [39]:
#Specify the size of each element in the numpy-array

print("a: ", a.itemsize, "bytes")   #64/8 = 8 bytes
print("b: ", b.itemsize, "bytes")   #64/8 = 8 bytes
print("e: ", e.itemsize, "bytes")   #16/8 = 2 bytes
print(f.itemsize, "bytes")   #16/6 = 2 bytes

8 bytes
8 bytes
2 bytes
2 bytes


In [42]:
#returns the snumber of elements in a numpy-array

print("size of a: ", a.size)
print("size of b: ", b.size)
print("size of c: ", c.size)
print("size of d: ", d.size)
print("size of e: ", e.size)
print("size of f: ", f.size)

size of a:  3
size of b:  3
size of c:  6
size of d:  6
size of e:  3
size of f:  3


In [45]:
#Finding the total number of bytes of the numpy-array

print("total number of bytes in a: ", a.size * a.itemsize)
print("total number of bytes in c: ", c.size * c.itemsize)
print("total number of bytes in e: ", e.size * e.itemsize)

total number of bytes in a:  24
total number of bytes in c:  48
total number of bytes in e:  6


In [61]:
#Accessing/Changing specific elements, rows, columns, etc

g = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])   #2x7 array
print(g, end = "\n\n")

#[row][col]

for r in range(2):
    for c in range(7):
        print(g[r][c], end = " ")

print("\n\n")

for r in range(2):
    for c in range(7):
        g[r][c] *= 2
        print(g[r][c], end = " ")

print("\n\n")

print(g[0][0], g[0][1], g[0][2], g[0][3], g[0][4], g[0][5], g[0][6])

print("\n")

print(g[1][0], g[1][1], g[1][2], g[1][3], g[1][4], g[1][5], g[1][6])

print("\n")

for r in range(2):
    for c in range(7):
        g[r][c] = 0
        print(g[r][c], end = " ")
        
print("\n")

print(g)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

1 2 3 4 5 6 7 8 9 10 11 12 13 14 


2 4 6 8 10 12 14 16 18 20 22 24 26 28 


2 4 6 8 10 12 14


16 18 20 22 24 26 28


0 0 0 0 0 0 0 0 0 0 0 0 0 0 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [75]:
#0-matrices

h = np.zeros(1)
i = np.zeros((2, 2), dtype = "int32")
j = np.zeros((3, 3), dtype = "int16")

print(h, "\n\n", "________________________________\n")
print(i, "\n\n", "________________________________\n")
print(j, "\n\n", "________________________________\n")

#2 x (2 x 2) matrices in a matrix

k = np.zeros((2, 2, 2))
print(k, "\n\n", "________________________________\n")

l = np.zeros((2, 2, 2, 2))
print(l, "\n\n", "________________________________\n")

[0.] 

 ________________________________

[[0 0]
 [0 0]] 

 ________________________________

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

 ________________________________

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] 

 ________________________________

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]] 

 ________________________________



In [74]:
#all-1 matrices

m = np.ones(1)
n = np.ones((2, 2), dtype = "int32")
o = np.ones((3, 3), dtype = "int16")

print(m, "\n\n", "________________________________\n")
print(n, "\n\n", "________________________________\n")
print(o, "\n\n", "________________________________\n")

#2 x (2 x 2) matrices in a matrix

p = np.ones((2, 2, 2))
print(p, "\n\n", "________________________________\n")

q = np.ones((2, 2, 2, 2))
print(q, "\n\n", "________________________________\n")

[1.] 

 ________________________________

[[1 1]
 [1 1]] 

 ________________________________

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

 ________________________________

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]] 

 ________________________________

[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]] 

 ________________________________



In [78]:
#Initiallizing all the elements of a numpy-matrix with a particular element

h = np.full(1, 1)
i = np.full((2, 2), 1, dtype = "int32")
j = np.full((3, 3), 99, dtype = "int16")

print(h, "\n\n", "________________________________\n")
print(i, "\n\n", "________________________________\n")
print(j, "\n\n", "________________________________\n")

#2 x (2 x 2) matrices in a matrix

k = np.full((2, 2, 2), 2)
print(k, "\n\n", "________________________________\n")

l = np.full((2, 2, 2, 2), 4)
print(l, "\n\n", "________________________________\n")


[1] 

 ________________________________

[[1 1]
 [1 1]] 

 ________________________________

[[99 99 99]
 [99 99 99]
 [99 99 99]] 

 ________________________________

[[[2 2]
  [2 2]]

 [[2 2]
  [2 2]]] 

 ________________________________

[[[[4 4]
   [4 4]]

  [[4 4]
   [4 4]]]


 [[[4 4]
   [4 4]]

  [[4 4]
   [4 4]]]] 

 ________________________________



In [79]:
#Random decimal numbers

m = np.random.rand(4, 2)

print(m)

array([[0.98660329, 0.62293185],
       [0.31058788, 0.00528383],
       [0.97632904, 0.50719846],
       [0.3056529 , 0.42735025]])

In [81]:
#Random integer numbers

n = np.random.randint(10, size = (3, 3))

print(n)

[[5 7 2]
 [4 3 5]
 [4 5 5]]


In [84]:
#Identity matrices

print(np.identity(1), "\n\n")
print(np.identity(2), "\n\n")
print(np.identity(3), "\n\n")
print(np.identity(4), "\n\n")
print(np.identity(5), "\n\n")

[[1.]] 


[[1. 0.]
 [0. 1.]] 


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 




In [89]:
o = np.ones((5, 5))

for i in range (1, 4):
    for j in range(1, 4):
        o[i][j] = 0

o[2][2] = 9

print(o)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [92]:
#Unlike in C/C++ "replica_arr" is not a copy of "np_arr", in fact it points towards the same thing

np_arr = np.array([1, 2, 3])

replica_arr = np_arr

np_arr[0] = 100
replica_arr[1] = 99   #Since they points towards the same memory changes in one array will impact it's replica

prin
t(np_arr)
print(replica_arr)

[100  99   3]
[100  99   3]


In [94]:
#To prevent the problem from above, we use "copy()" function

np_arr = np.array([1, 2, 3])

replica_arr = np_arr.copy()

np_arr[0] = 100
replica_arr[1] = 99   

print(np_arr)
print(replica_arr)

[100   2   3]
[ 1 99  3]


In [105]:
import math

matrix1 = np.array(([0, 90], [180, 270]))

matrix1 = np.array(([0, (math.pi / 4)], [math.pi, (math.pi + (math.pi / 4))]))

print(matrix1, "\n\n")

print(np.sin(matrix1))

[[0.         0.78539816]
 [3.14159265 3.92699082]] 


[[ 0.00000000e+00  7.07106781e-01]
 [ 1.22464680e-16 -7.07106781e-01]]


In [115]:
#Multiplication of 2 matrices

m1 = np.ones((2, 3))
m2 = np.full((3, 2), 2)

print("m1:\n\n", m1, "\n\n")
print("m2:\n\n", m2, "\n\n")

print("m1 x m2:\n\n", np.matmul(m1, m2), "\n\n")

m1:

 [[1. 1. 1.]
 [1. 1. 1.]] 


m2:

 [[2 2]
 [2 2]
 [2 2]] 


m1 x m2:

 [[6. 6.]
 [6. 6.]] 




In [116]:
#Finding the determinant

print(np.linalg.det(np.matmul(m1, m2)))   #(6 x 6) - (6 x 6)

0.0


In [126]:
#Basic statistics

stats = np.array([[2, 4, 6], [8, 10, 12]])
print(stats, "\n\n")

print(np.min(stats))
print(np.max(stats))

print(np.sum(stats))

[[ 2  4  6]
 [ 8 10 12]] 


2
12
42
