In [4]:
import numpy as np

a = np.arange(15)

print(a, "\n\n")

b = a.reshape(3, 5)   #3-rows, 5-columns

print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
#return the dimension of an array

print("dimension of a: ", a.ndim)
print("dimension of b: ", b.ndim)

dimension of a:  1
dimension of b:  2


In [8]:
#return the total number of elements in an array

print("total number of elements in a: ", a.size)
print("total number of elements in b: ", b.size)

total number of elements in a:  15
total number of elements in b:  15


In [9]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
#Numpy's classic way of creating an array

c = np.array([6, 7, 8])
print(c)

[6 7 8]


In [13]:
#return the data-type

print("datatype of a: ", a.dtype)
print("datatype of b: ", b.dtype)
print("datatype of c: ", c.dtype)

d = np.array([1.2, 3.5, 5.1])

print("datatype of d: ", d.dtype)

datatype of a:  int64
datatype of b:  int64
datatype of c:  int64
datatype of d:  float64


In [14]:
#Numpy's classic 2-D array

e = np.array([(1.5, 2, 3), (4, 5, 6)])

print(e)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [17]:
#All 0s array

f = np.zeros((3, 4))

print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
#All 1s array

g = np.ones((2, 3, 4), dtype = np.int16)   #There are 2 of 3 x 4 matrices of 1s

print(g)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [25]:
#Starting-point, Ending-point, step-size

h = np.arange(10, 30, 5)   #np.arrange(Starting-point, Ending-point, step-size)
i = np.arange(0, 2, 0.3)

print("h: ", h, "\n")
print("i: ", i, "\n")

h:  [10 15 20 25] 

i:  [0.  0.3 0.6 0.9 1.2 1.5 1.8] 



In [28]:
#"linspace" returns an array with specified number of elements witihin the interval

j = np.linspace(0, 10, 5)
k = np.linspace(2, 10, 5)
    
print("j: ", j, "\n")
print("k: ", k, "\n")

j:  [ 0.   2.5  5.   7.5 10. ] 

k:  [ 2.  4.  6.  8. 10.] 



In [35]:
#Basic operations

l = np.array([20, 30, 40, 50])
m = np.arange(4)   #does not include 4

print("l: ", l, "\n")
print("m: ", m, "\n")

print("l + m: ", l + m, "\n")
print("l x m: ", l * m, "\n")

l:  [20 30 40 50] 

m:  [0 1 2 3] 

l + m:  [20 31 42 53] 

l x m:  [  0  30  80 150] 



In [41]:
import math

n = np.array([0, (math.pi / 2), math.pi, ((math.pi / 2) + math.pi), (2 * math.pi)])

print(np.sin(a))


[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736]


In [44]:
#Boolean

o = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


print("o > 5: ", o > 5)

o > 5:  [False False False False False  True  True  True  True  True]


In [54]:
#Multiplication of matrices

p = np.array([[1, 1], [0, 1]])

q = np.array([[2, 0], [3, 4]])

print("p: \n", p, "\n\n")
print("q: \n", q, "\n\n")

#Element-wise multiplication

print("p * q: \n", p * q, "\n\n")

#Matrix multiplication

print("p @ q: \n", p @ q, "\n\n")

print("p.dot(q): \n", p.dot(q), "\n\n")

p: 
 [[1 1]
 [0 1]] 


q: 
 [[2 0]
 [3 4]] 


p * q: 
 [[2 0]
 [0 4]] 


p @ q: 
 [[5 4]
 [3 4]] 


p.dot(q): 
 [[5 4]
 [3 4]] 




In [62]:
#Summing all the elements in the array

print("p.sum(): ", p.sum())
print("p.min(): ", p.min(), "\n\n")

print("q.sum(): ", q.sum())
print("q.max(): ", q.max(), "\n\n")

p.sum():  3
p.min():  0 


q.sum():  9
q.max():  4 




In [64]:
r = np.arange(12).reshape(3, 4)

print(r)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [67]:
#Sum of each column

print("Column sum: ", r.sum(axis = 0))

#Sum of each row

print("Row sum: ", r.sum(axis = 1))


Column sum:  [12 15 18 21]
Row sum:  [ 6 22 38]


In [70]:
#Cumulative sum of each 

print("Cumulative column sum: ", r.cumsum(axis = 0), "\n\n")
print("Cumulative row sum: ", r.cumsum(axis = 1))

Cumulative column sum:  [[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]] 


Cumulative row sum:  [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [73]:
#Square rooting

s = np.array([[1, 4, 9], [16, 25, 36]])

print(np.sqrt(s))

[[1. 2. 3.]
 [4. 5. 6.]]


In [84]:
#Indexing, Slicing and Iterating

t = np.arange(10) ** 3

print("t: ", t)
print("t[2 : 5]: ", t[2: 5])   #Starting from index-2 up to but not including the index-5
print("t[ : 6 : 2]: ", t[ : 6 : 2])   #Starting from index-0 up to but not inclduding index-6, step-size 2

t[ : 6 : 2] = 0

print("t: ", t)

t:  [  0   1   8  27  64 125 216 343 512 729]
t[2 : 5]:  [ 8 27 64]
t[ : 6 : 2]:  [ 0  8 64]
t:  [  0   1   0  27   0 125 216 343 512 729]


In [86]:
#Print individual rows in the matrix

for row in s:
    print(row)


[1 4 9] [16 25 36] 

In [97]:
#Transposition

u = np.array([3, 7, 3, 4, 1, 4, 2, 2, 7, 2, 4, 9])

print(u, "\n\n")

s = u.reshape(6, 2)

print(s, "\n\n")

print("s dimensions: ", s.shape, "\n\n")
print("s Transposed dimensions: ", s.T.shape, "\n\n")
print(s.T)

[3 7 3 4 1 4 2 2 7 2 4 9] 


[[3 7]
 [3 4]
 [1 4]
 [2 2]
 [7 2]
 [4 9]] 


s dimensions:  (6, 2) 


s Transposed dimensions:  (2, 6) 


[[3 3 1 2 7 4]
 [7 4 4 2 2 9]]


In [107]:
"""
The "reshape" function returns its argument with a modified shape, wheras "ndarray.resize" method modifies the 
array itself.
"""

print(r, "\n\n")

r.reshape((6, 2))

print(r, "\n\n")

r.resize((6, 2))

print(r, "\n\n")

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 


